// Code generated by "stringer -type=VikunjaActionType"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TaskCreated-1]
}

const _VikunjaActionType_name = "TaskCreated"

var _VikunjaActionType_index = [...]uint8{0, 11}

func (i VikunjaActionType) String() string {
	i -= 1
	if i < 0 || i >= VikunjaActionType(len(_VikunjaActionType_index)-1) {
		return "VikunjaActionType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _VikunjaActionType_name[_VikunjaActionType_index[i]:_VikunjaActionType_index[i+1]]
}
